### PR TITLE
adding 72edo notation support in sc

### PR DESCRIPTION
**Pull request by levinericzimmermann**
Hi Michael,

with few changes it is possible to support twelfth-tone notation in Lilypond output. Thomas Richter wrote the beautiful Lilypond extension [Ekmelily](http://www.ekmelic-music.org/en/extra/ekmelily.htm) which improves flexibility for microtonal notation. Because twelfth-tones are already implemented in slippery-chicken, it is very easy to notate them when using Richters extension:

1. I had to comment few lines in pitch.lsp that round twelfth-tones to quarter-tones.
2. I added few lines in slippery-chicken.lsp that import the Ekmelily extension and that set its accidentals style (Ekmelily supports different styles). Perhaps it is more elegant to add the accidental-style as an optional argument for the write-lp-data-for-all method.
3. I had to tweak one file of Richters extension (my outcome is emel-sc.ily). Unfortunately slippery-chicken and Ekmelily use different nomenclature for twelfth-tones. Because I personally find slippery-chickens nomenclature more intuitive I decided to change Ekmelily. If I'm not mistaken my laziness forced me to only change the names for accidentals of the closest diatonic pitch (e.g. I didn't adapt the name for +/- 13/12 tone). 

Anyone who would like to use twelfth-tone notation would still have to install Ekmelily and Ekmelos (the corresponding font) first. Because Lilypond will raise an error when trying to include Ekmelily while it hasn't been installed yet, I added the key argument use-ekmelily in write-lp-data-for-all.

Best, Levin

### CODE REVIEW

**Comment by mdedwards** [comment]
That's great, thanks for this Levin. I'm really busy preparing classes at the moment so might need a little while to get to this. In the meantime, did you modify the latest code from the 'michael' branch to achieve this or the main branch (or something even older)? Plus, did you run the regression tests with your additions? No problem if not, I'd just be interested to know if they worked for you. Best, Michael

**Comment by danieljamesross** [comment]
Nice work, @levinericzimmermann, will be sure to check this out later!

> Unfortunately slippery-chicken and Ekmelily use different nomenclature for twelfth-tones. Because I personally find slippery-chickens nomenclature more intuitive I decided to change Ekmelily.

Perhaps a future-proof method would be a small helper function which converts from one format to another? THis could even be hardcoded.

**Comment by levinericzimmermann** [comment]
@mdedwards I guess I cloned the master branch. Ehhm if you can tell me where I can find the tests, I could try to run them (although I can only think of the change in pitch.lsp to produce an error).

@danieljamesross Thanks, I think that's a good idea. Writing a small function that translates the format would certainly be a cleaner solution. And since I assume that Richter won't change the nomenclature in the course of further development, hard-coding the translation may be sufficient. When using a translation function, we also wouldn't need to add the ekmel-sc.ily file.

> Anyone who would like to use twelfth-tone notation would still have to install Ekmelily and Ekmelos (the corresponding font) first. 

In case of adding the 72edo notation support, it may be a good idea to mention Ekmelily in the [installation guide](https://github.com/mdedwards/slippery-chicken/wiki/how-to-install-slippery-chicken-'by-hand').

**Comment by mdedwards** [comment]
Switch to the michael branch perhaps then branch your stuff again? this kind of thing definitely needs to be on the michael branch as that's the 'bleeding edge'

The tests are (still, at the moment) a separate project: https://github.com/mdedwards/slippery-chicken-RTs
Don't worry about that though unless you think you'd like to run those yourself occasionally.

Let's talk about this soon....busy making teaching videos etc. at the mo.

**Comment by levinericzimmermann** [comment]
Hi everyone, as discussed few days ago with Michael I tried implementing the notation via defining a new common-music scale in cm-load.lsp with the respective nomenclatura of Ekmelily. Unfortunately I run into errors when calling lp-display due to hard-coded accidentals in the 'set-white-note' method. Shall we adapt the set-white-note method (and all other methods where accidentals are hard-coded, if there are any) or better return to the previous method of translating sc default twelfth-tone accidentals to Ekmelily accidentals?

**Comment by mdedwards** [comment]
Hi Levin, I would say it's better to add the accidentals to the `case` tests in set-white note. The ekmeilily stuff should be coded and handled like any of the existing scales, as far as that's feasible.

**Comment by levinericzimmermann** [comment]
Alright, I've added the ekmelily scale as an additional cm-scale in [this pull request](https://github.com/mdedwards/slippery-chicken/pull/42)/.

**Pull request closed without merging**
