### PR TITLE
use envelopes as argument for src-scaler and duration-scaler in clm-play

### PR DESCRIPTION
**Pull request by Leon-Focker**

### CODE REVIEW

**Comment by danieljamesross** [comment]
This is really cool. Is there an example and some tests I can see, please?

**Comment by Leon-Focker** [comment]
> This is really cool. Is there an example and some tests I can see, please?
Thanks! Yes, of course. I tested it within a piece I am working on. Here is a .wav file straight out of slippery chicken:

http://icem.folkwang-uni.de/~focker/share/clm-play-envelopes.wav

...which I got using those envelopes:

     :duration-scaler '(0 0.1  80 3  100 0.1)
     :src-scaler '(0 1  20 2  45 0.5  100 1)

**Comment by danieljamesross** [comment]
Oh I mean regression tests. We need to make sure that the new feature doesn't unintentionally break older methods.

ll 17473

**Comment by Leon-Focker** [comment]
Ah, I have run the (run-tests) function, which should do exactly that, right? All tests were passed.
Should I do anything else?

**Comment by danieljamesross** [comment]
You'll need to also write a test for the new feature and show a minimal working example. Something like:

```lisp
(let ((mini (make-slippery-chicken... )))
  (clm-play [...]
    :duration-scaler '(0 0.1  80 3  100 0.1)))
```

In fact, there should be a test and example for each. You should also updated the documentation (the clm-play comments in the file).

**Comment by mdedwards** [comment]
Nice work Leon! I've merged your pull request and can confirm that the new code passes all the tests for me also.

**Pull request merged**
